# frozen_string_literal: true

source "https://rubygems.org"

# Use GitHub Pages gem for compatibility
gem "github-pages", group: :jekyll_plugins

# Bailey3D: Fix for live reload not working
#           See: https://stackoverflow.com/questions/30682575/unable-to-load-the-eventmachine-c-extension-to-use-the-pure-ruby-reactor
gem 'eventmachine', '1.2.7', git: 'https://github.com/eventmachine/eventmachine.git', tag: 'v1.2.7'

# Additional plugins not included in github-pages
group :jekyll_plugins do
    gem 'jekyll-redirect-from'
end

